#!/usr/bin/env bash
# Script displays list of currently running processes
# Shows all processes, for all users, including those which might not have a TTY
# Displays a user-oriented format
# Shows process hierarchy

ps -auxf
