#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
# Displaying "bad luck from China" for the 4th iteration
# Displays  "bad luck from Japan" for the 9th iteration
# On the 17th iteration displays "bad luck from Italy"

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
